///
/// HybridCurrencyPickerViewComponent.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

#include "HybridCurrencyPickerViewComponent.hpp"

#include <string>
#include <exception>
#include <utility>
#include <NitroModules/NitroDefines.hpp>
#include <NitroModules/JSIConverter.hpp>
#include <react/renderer/core/RawValue.h>
#include <react/renderer/core/ShadowNode.h>
#include <react/renderer/core/ComponentDescriptor.h>
#include <react/renderer/components/view/ViewProps.h>

namespace margelo::nitro::onchain::views {

  extern const char HybridCurrencyPickerViewComponentName[] = "CurrencyPickerView";

  HybridCurrencyPickerViewProps::HybridCurrencyPickerViewProps(const react::PropsParserContext& context,
                                                               const HybridCurrencyPickerViewProps& sourceProps,
                                                               const react::RawProps& rawProps):
    react::ViewProps(context, sourceProps, rawProps, filterObjectKeys),
    enableFlash([&]() -> CachedProp<bool> {
      try {
        const react::RawValue* rawValue = rawProps.at("enableFlash", nullptr, nullptr);
        if (rawValue == nullptr) return sourceProps.enableFlash;
        const auto& [runtime, value] = (std::pair<jsi::Runtime*, jsi::Value>)*rawValue;
        return CachedProp<bool>::fromRawValue(*runtime, value, sourceProps.enableFlash);
      } catch (const std::exception& exc) {
        throw std::runtime_error(std::string("CurrencyPickerView.enableFlash: ") + exc.what());
      }
    }()),
    hybridRef([&]() -> CachedProp<std::optional<std::function<void(const std::shared_ptr<margelo::nitro::onchain::HybridCurrencyPickerViewSpec>& /* ref */)>>> {
      try {
        const react::RawValue* rawValue = rawProps.at("hybridRef", nullptr, nullptr);
        if (rawValue == nullptr) return sourceProps.hybridRef;
        const auto& [runtime, value] = (std::pair<jsi::Runtime*, jsi::Value>)*rawValue;
        return CachedProp<std::optional<std::function<void(const std::shared_ptr<margelo::nitro::onchain::HybridCurrencyPickerViewSpec>& /* ref */)>>>::fromRawValue(*runtime, value.asObject(*runtime).getProperty(*runtime, "f"), sourceProps.hybridRef);
      } catch (const std::exception& exc) {
        throw std::runtime_error(std::string("CurrencyPickerView.hybridRef: ") + exc.what());
      }
    }()) { }

  HybridCurrencyPickerViewProps::HybridCurrencyPickerViewProps(const HybridCurrencyPickerViewProps& other):
    react::ViewProps(),
    enableFlash(other.enableFlash),
    hybridRef(other.hybridRef) { }

  bool HybridCurrencyPickerViewProps::filterObjectKeys(const std::string& propName) {
    switch (hashString(propName)) {
      case hashString("enableFlash"): return true;
      case hashString("hybridRef"): return true;
      default: return false;
    }
  }

  HybridCurrencyPickerViewComponentDescriptor::HybridCurrencyPickerViewComponentDescriptor(const react::ComponentDescriptorParameters& parameters)
    : ConcreteComponentDescriptor(parameters,
                                  react::RawPropsParser(/* enableJsiParser */ true)) {}

  react::Props::Shared HybridCurrencyPickerViewComponentDescriptor::cloneProps(const react::PropsParserContext& context,
                                                                               const react::Props::Shared& props,
                                                                               react::RawProps rawProps) const {
    // 1. Prepare raw props parser
    rawProps.parse(rawPropsParser_);
    // 2. Copy props with Nitro's cached copy constructor
    return HybridCurrencyPickerViewShadowNode::Props(context, /* & */ rawProps, props);
  }

#ifdef ANDROID
  void HybridCurrencyPickerViewComponentDescriptor::adopt(react::ShadowNode& shadowNode) const {
    // This is called immediately after `ShadowNode` is created, cloned or in progress.
    // On Android, we need to wrap props in our state, which gets routed through Java and later unwrapped in JNI/C++.
    auto& concreteShadowNode = dynamic_cast<HybridCurrencyPickerViewShadowNode&>(shadowNode);
    const HybridCurrencyPickerViewProps& props = concreteShadowNode.getConcreteProps();
    HybridCurrencyPickerViewState state;
    state.setProps(props);
    concreteShadowNode.setStateData(std::move(state));
  }
#endif

} // namespace margelo::nitro::onchain::views
