///
/// HybridCurrencyPickerViewComponent.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

#pragma once

#include <optional>
#include <NitroModules/NitroDefines.hpp>
#include <NitroModules/NitroHash.hpp>
#include <NitroModules/CachedProp.hpp>
#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewProps.h>

#include <optional>
#include <functional>
#include <memory>
#include "HybridCurrencyPickerViewSpec.hpp"

namespace margelo::nitro::onchain::views {

  using namespace facebook;

  /**
   * The name of the actual native View.
   */
  extern const char HybridCurrencyPickerViewComponentName[];

  /**
   * Props for the "CurrencyPickerView" View.
   */
  class HybridCurrencyPickerViewProps final: public react::ViewProps {
  public:
    HybridCurrencyPickerViewProps() = default;
    HybridCurrencyPickerViewProps(const HybridCurrencyPickerViewProps&);
    HybridCurrencyPickerViewProps(const react::PropsParserContext& context,
                                  const HybridCurrencyPickerViewProps& sourceProps,
                                  const react::RawProps& rawProps);

  public:
    CachedProp<bool> enableFlash;
    CachedProp<std::optional<std::function<void(const std::shared_ptr<margelo::nitro::onchain::HybridCurrencyPickerViewSpec>& /* ref */)>>> hybridRef;

  private:
    static bool filterObjectKeys(const std::string& propName);
  };

  /**
   * State for the "CurrencyPickerView" View.
   */
  class HybridCurrencyPickerViewState final {
  public:
    HybridCurrencyPickerViewState() = default;

  public:
    void setProps(const HybridCurrencyPickerViewProps& props) { _props.emplace(props); }
    const std::optional<HybridCurrencyPickerViewProps>& getProps() const { return _props; }

  public:
#ifdef ANDROID
  HybridCurrencyPickerViewState(const HybridCurrencyPickerViewState& /* previousState */, folly::dynamic /* data */) {}
  folly::dynamic getDynamic() const {
    throw std::runtime_error("HybridCurrencyPickerViewState does not support folly!");
  }
  react::MapBuffer getMapBuffer() const {
    throw std::runtime_error("HybridCurrencyPickerViewState does not support MapBuffer!");
  };
#endif

  private:
    std::optional<HybridCurrencyPickerViewProps> _props;
  };

  /**
   * The Shadow Node for the "CurrencyPickerView" View.
   */
  using HybridCurrencyPickerViewShadowNode = react::ConcreteViewShadowNode<HybridCurrencyPickerViewComponentName /* "HybridCurrencyPickerView" */,
                                                                           HybridCurrencyPickerViewProps /* custom props */,
                                                                           react::ViewEventEmitter /* default */,
                                                                           HybridCurrencyPickerViewState /* custom state */>;

  /**
   * The Component Descriptor for the "CurrencyPickerView" View.
   */
  class HybridCurrencyPickerViewComponentDescriptor final: public react::ConcreteComponentDescriptor<HybridCurrencyPickerViewShadowNode> {
  public:
    HybridCurrencyPickerViewComponentDescriptor(const react::ComponentDescriptorParameters& parameters);

  public:
    /**
     * A faster path for cloning props - reuses the caching logic from `HybridCurrencyPickerViewProps`.
     */
    react::Props::Shared cloneProps(const react::PropsParserContext& context,
                                    const react::Props::Shared& props,
                                    react::RawProps rawProps) const override;
#ifdef ANDROID
    void adopt(react::ShadowNode& shadowNode) const override;
#endif
  };

  /* The actual view for "CurrencyPickerView" needs to be implemented in platform-specific code. */

} // namespace margelo::nitro::onchain::views
