///
/// HybridCurrencyPickerViewSpec.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

#include "HybridCurrencyPickerViewSpec.hpp"

namespace margelo::nitro::onchain {

  void HybridCurrencyPickerViewSpec::loadHybridMethods() {
    // load base methods/properties
    HybridObject::loadHybridMethods();
    // load custom methods/properties
    registerHybrids(this, [](Prototype& prototype) {
      prototype.registerHybridGetter("enableFlash", &HybridCurrencyPickerViewSpec::getEnableFlash);
      prototype.registerHybridSetter("enableFlash", &HybridCurrencyPickerViewSpec::setEnableFlash);
    });
  }

} // namespace margelo::nitro::onchain
